### ISSUE TITLE
Definiciones de Typescript

### ISSUE THREAD

**Issue by AlanOrtega91** [FacturAPI/facturapi-node#10]
Estaría increíble que se pudieran incluir las definiciones en typescript para poder utilizar de una mejor manera la librería.
Implementare algunas definiciones para mi proyecto y las pondré aquí cuando acabe, espero puedan servir.

**Comment by ningacoding** [comment]
Es un buen Feature request

**Comment by CarlosEscBaz** [comment]
¿Hay algún avance con esto? Me serviría bastante.

**Comment by ferpinedo** [comment]
Pueden descargar la especificación de OpenAPI que está en la documentación oficial de Facurapi: [docs.facturapi.io/api/](https://docs.facturapi.io/api/) y generar los tipos con esta librería: [openapi-typescript](https://www.npmjs.com/package/openapi-typescript).

También pueden crear un cliente con esos tipos generados utilizando la misma librería. Les recomiendo seguir [estos pasos](https://github.com/drwpow/openapi-typescript/tree/main/packages/openapi-fetch#-setup).

**Comment by javorosas** [comment]
@ferpinedo Gracias por el consejo, vamos a explorar esa posibilidad
