### ISSUE TITLE
Filtrado de facturas por "Métodos de pago" - PPD

### ISSUE THREAD

**Issue by MichFe** [FacturAPI/facturapi-node#13]
Hola @javorosas , 

**Summary:**
Este es un **feature request** para un end point en su API que nos permita obtener una lista de facturas filtrando el campo "Métodos de pago", el objetivo es poder generar fácilmente vistas con las facturas PPD para posteriormente crear "Facturas de Recepción de Pagos" sobre las mismas.

Otra opción sería agregar un end point que nos permita enviar un objeto query para poder filtrar nuestras facturas.

Saludos!
MF

**Comment by javorosas** [comment]
Hola. Esta semana añadimos esta funcionalidad a la API. Para filtrar por método de pago puedes usar el parámetro `payment_method` en el query de búsqueda.
