### ISSUE TITLE
Error subiendo archivos con encoding 7bit

### ISSUE THREAD

**Issue by AbrahamJoseKazerian** [FacturAPI/facturapi-node#15]
El upload de archivos que tiene son cer y key para CSD con un encoding de 7bit falla. Es esto un resultado esperado ?

![image](https://user-images.githubusercontent.com/43617525/97007949-8d5cce00-1518-11eb-8c77-d9c84f3bbe12.png)

**Comment by javorosas** [comment]
Hola Abraham. Disculpa la demora.

Cómo conseguiste generar el CSD con ese encoding? Funciona si usas alguna herramienta para convertirlo a utf8?

El caso ideal es que se convierta automáticamente, pero pregunto para saber si hacer eso de nuestro lado resolvería el problema o no
