### ISSUE TITLE
problems with receipts.createGlobalInvoice

### ISSUE THREAD

**Issue by sznrbrt** [FacturAPI/facturapi-node#18]
Hi Team, 

When I try to create a Global invoice in test mode, the request comes back with 200 OK, but the response is empty. No error comes back. I checked the logs coming back from axios directly in the library, but no response is present.

I tried sending it with empty parameters and with from, to, series defined as well but the response is the same:

`await facturapi.receipts.createGlobalInvoice({});`

**Comment by javorosas** [comment]
This is the expected behavior when there are no open receipts left to put into the global invoice for that time period.
