### ISSUE TITLE
Problema al subir certificados (key, cer)

### ISSUE THREAD

**Issue by gmwill934** [FacturAPI/facturapi-node#22]
Estoy implementando en una API REST la funcionalidad de subir los archivos:

`.key`
`.cer`

Estoy siguiendo la documentación de facturapi (https://docs.facturapi.io/api/#operation/uploadOrganizationCertificate)

```
    const key = createReadStream(
      'absolute/path',
    );
    const cer = createReadStream(
      'absolute/path',
    );
    await this.facturapi.organizations.uploadCertificate(
      tenant.facturapiOrganizationId,
      cer,
      key,
      uploadCertificatePasswordDto.password,
    );

```
El error que me arroja es

`Error: El certificado no es un CSD válido. Asegúrate de que se trate del CSD y no de la FIEL.`

NOTA: Ya intente de iniciar sesión en el SAT con mi `.cer` y `.key` y contraseña y si funciona.

¿algo que se me este pasando?

**Comment by gmwill934** [comment]
![Screen Shot 2022-01-03 at 22 38 31](https://user-images.githubusercontent.com/65828254/148010325-c935eb46-5110-4059-8b76-ba40517bb2d7.png)

**Comment by farivasf11** [comment]
Creo que el problema que están presentando es debido a que los archivos .cer y .key que necesita la api son los del Certificado de Sello Digital, y no los de la FIEL, ya que son distintos.
Se puede encontrar información para generar dichos archivos en esta [página](https://www.sat.gob.mx/aplicacion/16660/genera-y-descarga-tus-archivos-a-traves-de-la-aplicacion-certifica).
