### ISSUE TITLE
Solo se puede utilizar el sello digital?

### ISSUE THREAD

**Issue by NTHINGs** [FacturAPI/facturapi-node#4]
Buen día, excelente proyecto. Pero no me es posible utilizarlo ya que solo tengo mi FIEL y en la herramienta gratuita del SAT siempre he sellado mis facturas con la FIEL.

**Comment by javorosas** [comment]
Nota para la posteridad: Tus facturas no pueden ser válidas si sólo las sellas (sin timbrar). Tampoco pueden ser válidas si no usas los Certificados de Sello Digital (CSD) para firmarlas. El objetivo de esta librería es generar facturas válidas (en modo Live o Producción), o una simulación, no-válidas, (en modo Testing o Pruebas) pero sólo por motivos de pruebas con desarrollo.

Si lo que se busca es poder hacer pruebas sin todavía tener un certificado (para que los developers no necesiten un certificado), estamos trabajando en soportar un certificado genérico para pruebas. Es decir, que el método de Crear Factura en modo Testing no requiera haber subido un certificado válido.
