### ISSUE TITLE
Propuesta de Integración de Zod para Mejorar la Validación de Tipos

### ISSUE THREAD

**Issue by Serlych** [FacturAPI/facturapi-node#44]
## ¡Hola!

Quiero comenzar expresando mi admiración y agradecimiento por el excepcional trabajo que realizan manteniendo esta biblioteca. Gracias a su esfuerzo, usuarios como yo podemos disfrutar de una herramienta tan útil y fácil de utilizar. ¡Felicidades!

## Sugerencia 

Les escribo para sugerir la integración de una biblioteca llamada [Zod](https://zod.dev/), que facilita la validación de tipos en tiempo de ejecución y permite generar tipos de TypeScript a partir de los esquemas definidos. Creo que podría complementar muy bien el trabajo que ya están haciendo, especialmente considerando que están trabajando en una adaptación a TypeScript.

Aquí les comparto algunos tipos que he creado en mi proyecto, aprovechando su excelente documentación en https://docs.facturapi.io/:

```typescript

export const createOrganizationAddressDto = z.object({
  zip: z.string(),
  street: z.string(),
  exterior: z.string(),
  interior: z.string().optional(),
  neighborhood: z.string().optional(),
  city: z.string().optional(),
  municipality: z.string().optional(),
  state: z.string().optional(),
});
export type CreateOrganizationAddresseDto = z.infer<
  typeof createOrganizationAddressDto
>;

export const createOrganizationDto = z.object({
  name: z.string(),
  legal_name: z.string(),
  tax_system: z.string(),
  certificates: certificatesDto,
  website: z.string().optional(),
  support_email: z.string().optional(),
  phone: z.string().optional(),
  supabase_project_id: z.string(),
  address: createOrganizationAddressDto,
});
export type CreateOrganizationDto = z.infer<typeof createOrganizationDto>;

export type UpdateOrganizationResponse = {
  id: string;
  created_at: string;
  is_production_ready: boolean;
  pending_steps: PendingStep[];
  legal: LegalInfo;
  customization: Customization;
  certificate: Certificate;
};
```

## Ejemplo de implementación

En este ejemplo, hago la implementación de la librería utilizando este endpoint:
https://github.com/FacturAPI/facturapi-node/blob/981e9f68e46c2e59aaa76d060ad5fcc9c89c7208/src/resources/organizations.ts#L48

```typescript 
// organizations.types.ts
import { z } from 'zod';

export const createOrganizationDto = z.object({
  name: z.string(),
  legal_name: z.string(),
  tax_system: z.string(),
  certificates: certificatesDto, // Asumiendo que certificatesDto está definido adecuadamente
  website: z.string().optional(),
  support_email: z.string().optional(),
  phone: z.string().optional(),
  supabase_project_id: z.string(),
  address: createOrganizationAddressDto, // Asumiendo que createOrganizationAddressDto está definido adecuadamente
});

export type CreateOrganizationDto = z.infer<typeof createOrganizationDto>;

// src/resources/organizations.ts
updateLegal(id: string, data: CreateOrganizationDto) {
  if (!id) return Promise.reject(new Error('id is required'));
  
  // Validar data usando el esquema de Zod
  const validation = createOrganizationDto.safeParse(data);
  if (!validation.success) {
    return Promise.reject(new Error('Validation failed: ' + validation.error.message));
  }

  // Si la validación es exitosa, proceder con la petición
  return this.client
    .put('/organizations/' + id + '/legal', data)
    .then((r) => r.data);
}

```

Como pueden observar, la implementación requerida para cada endpoint es mínima, mientras que los beneficios que aporta a la biblioteca son significativos.

## Ventajas de integrar Zod

1. Los tipos son más explícitos, facilitando la comprensión de los campos necesarios.
2. Evita el uso de tipos genéricos como `Record<string, string>`, reemplazándolos por estructuras más legibles.
3. Permite validar los esquemas antes de realizar las peticiones, optimizando el uso del ancho de banda.
4. Mejora la experiencia de desarrollo al simplificar la interacción con la API.
5. Se alinea con las prácticas estándar de la industria, especialmente útil en el contexto del rewrite a TypeScript que están realizando en este momento.
6. Aumenta la mantenibilidad del código al usar tipos definidos claramente.
7. Zod proporciona errores detallados y descriptivos que pueden ayudar significativamente durante el desarrollo y la depuración. 
8. Zod permite componer esquemas más complejos a partir de esquemas más simples. Esto es útil para mantener el código limpio y organizado.
9. Zod permite agregar validaciones personalizadas a los esquemas, lo que ofrece flexibilidad para implementar reglas de negocio específicas sin complicar el uso de la biblioteca o los tipos generados.
10. Los esquemas definidos en Zod pueden utilizarse para generar datos de prueba, lo que facilita escribir pruebas unitarias más robustas y fiables.

## ¡Gracias!

Estoy completamente dispuesto a enviarles el resto del código y colaborar estrechamente con ustedes en este esfuerzo.

**Comment by javorosas** [comment]
Hola @Serlych 👋

Muchas gracias por este issue y tu valiosa recomendación. Vamos a explorar este camino para manejar nuestro tipado.

**Comment by javorosas** [comment]
Hola @Serlych. Revisé Zod e hice algunas pruebas de concepto. Mi conclusión es que no es la herramienta que necesitamos actualmente.

Del lado de la API ya tenemos una herramienta de validación similar. No creo conveniente añadir otra capa de validación con la misma lógica del lado del cliente.

Por el momento vamos a optar por hacer los tipos a mano. Pero gracias por la recomendación.
