### ISSUE TITLE
Crear Organizaciones por medio de API

### ISSUE THREAD

**Issue by ningacoding** [FacturAPI/facturapi-node#6]
Es una solicitud de nueva funcionalidad más que un "issue":

- Poder crear Organizaciones programática-mente por medio de la API.

Algo como:

```
const facturapi = require('facturapi')('YOUR_API_KEY');

facturapi.organizations.create({
    comercialName: 'Nombre Comercial',
    legalName: 'Razón Social',
    // other required fields
}).then(organization=> {
    // Remember to store the organization.id in your records.
}).catch(err => console.log(err));
```

Y poder subirle los Certificados por medio de otras APIs.

Crear organizaciones por medio de la consola web es un poco engorroso, inseguro, manual y limitado.

Por lo tanto el "YOUR_API_KEY" debería ser único y para identificar una sola cuenta de facturapi.

**Comment by javorosas** [comment]
Resuelto en #9

Puedes ver cómo crear organizaciones en nuestra documentación: http://docs.facturapi.io/#organizaciones
